config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  root to: 'about#index'

  resources :pages, only: %i[index show]
  resources :about, only: [:index]
  # 親子関係
  resources :posts do
    resources :comments
    resources :likes, only: [:create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
# frozen_string_literal: true

class Comment < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :post, foreign_key: 'post_id'
  counter_culture :post
  validates :content, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  counter_culture :post
  validates :user_id, presence: true
  validates :post_id, presence: true
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :lesson_at, presence: true
  validates :place, presence: true
  validates :tag_list, presence: true

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  acts_as_taggable

  # ユーザが持っているいいねを探すメソッド
  def like_user(user_id)
    likes.find_by(user_id: user_id)
  end

#   # ransack　検索できるカラムの制限
#   def .ransackable_attributes(auth_object = nil)
#     %w[tags_name]
#   end

#   def self.ransackable_associations(auth_object = nil)
#     []
#   end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, presence: true, length: { maximum: 20 }
  validates :description, length: { maximum: 1000 }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable, omniauth_providers: [:twitter]

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  mount_uploader :avatar, AvatarUploader

  def self.from_omniauth(auth)
    find_or_create_by(provider: auth['provider'], uid: auth['uid']) do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.username = auth['info']['nickname']
      # user.remote_avatar_url = auth['info']['image']
      # user.email = User.dummy_email(auth)
      # user.password = Devise.friendly_token[0, 20]
    end
  end

  def self.new_with_session(params, session)
    if session['devise.user_attributes']
      new(session['devise.user_attributes']) do |user|
        user.attributes = params
      end
    else
      super
    end
  end

  def remember_me
    true
  end

  # private

  # def self.dummy_email(auth)
  #   "#{auth.uid}-#{auth.provider}@example.com"
  # end
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :tags_search

  def after_sign_in_path_for(_resource)
    flash.notice = "こんにちは、#{current_user.username} さん！"
    posts_path
  end

  def tags_search
    @q = Post.ransack(params[:q])
  end

  private

  def sign_in_required
    redirect_to new_user_session_url unless user_signed_in?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar, :description])
  end
end

app/controllers/comments_controller.rb
# frozen_string_literal: true

class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = current_user.comments.new(comment_params)
    @comment.post_id = @post.id
    @comment.user_id = current_user.id
    if @comment.save
      render :index
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    if @comment.destroy
      render :index
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_post

  def create
    @like = Like.create(user_id: current_user.id, post_id: params[:post_id])
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  def destroy
    like = Like.find_by(user_id: current_user.id, post_id: params[:post_id])
    like.destroy
    @likes = Like.where(post_id: params[:post_id])
    @post.reload
  end

  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class OmniauthCallbacksController < ApplicationController
  def twitter
    @user = User.from_omniauth(request.env['omniauth.auth'].except('extra'))

    if @user.persisted?
      flash.notice = "こんにちは、#{@user.username} さん！"
      sign_in_and_redirect @user
    else
      session['devise.user_attributes'] = @user.attributes
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[edit destroy update]

  def index
    @posts = @q.result(distinct: true).order(created_at: :desc).page(params[:page]).per(5)
    @post = Post.new
    @user = User.find_by(id: @post.user_id)
    if params[:tag_name]
      @posts = @posts.tagged_with(params[:tag_name])
    end
  end

  def show
    @post = Post.find(params[:id])
    @comment = Comment.new
    @comments = @post.comments
    @user = User.find_by(id: @post.user_id)
  end

  def new
    @post = current_user.posts.new
  end

  def edit; end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: "レッスン「#{@post.name}」を更新しました。"\
    else
      render :edit
    end
  end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to @post, notice: "レッスン「#{@post.name}」を登録しました。"
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post_id = @post.id
    if @post.destroy
      render :destroy
    end
  end

  private

  def post_params
    params.require(:post).permit(:name, :description, :lesson_at, :place, :tag_list)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_user?(user)
    user == current_user
  end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/about/index.html.slim
.top.text-center.bg-dark.my-4.py-5
  span style=("font-size: 7em; color: white;")
    i.fas.fa-laptop-code
    | Lesson
  p.text-white
    | Lessonとは、オフライン上で気軽に授業の場を提供するサービスです。
  - if user_signed_in?
    = link_to 'Lesson を見る', posts_path, class: 'btn btn-info btn-lg mt-3'
  - else
    = link_to "Lesson を始める", new_user_registration_path, class: 'btn btn-info btn-lg mt-3'
    = link_to 'Lesson を見る', posts_path, class: 'btn btn-info btn-lg mt-3 ml-2'
br
.container.mt-5
  .row.justify-content-center
    .col-xs-12.col-md-2
      i.fas.fa-users.fa-5x
    .col-xs-12.col-md-7
      p.py-auto
        | 「初心者だから、環境構築を一人でできる自信がない…」
        br
        | 「有識者に直接わかりやすく教えてもらいたい！」
        br
        | Lessonは、そのような悩みを解決するサービスです。
      br
    .col-xs-12.col-md-7
      p.py-auto
        | 技術やプログラミング言語に応じてレッスンを検索することもできます。
        br
        | まずは気軽にレッスンの予定を投稿してみよう！
    .col-xs-12.col-md-2
      i.fas.fa-terminal.fa-5x

app/views/comments/_form.html.slim
= form_with(model: [post,comment]) do |f|
  .form-group
    = f.text_area :content, class: 'form-control', id: 'text_area', placeholder: "コメントしてみよう！"
  = f.submit "コメントする", class: "btn btn-info"

app/views/comments/_index.html.slim
- comments.each do|comment|
  - unless comment.id.nil?
    div.fa-border
      p= link_to "#{comment.user.username}", page_path(comment.user.id)
      p
        |コメント:#{comment.content}
      p
        |#{comment.created_at}
      - if comment.user == current_user
        p= link_to 'コメントを削除する', post_comment_path(comment.post_id, comment.id), method: :delete, remote: true, data: { confirm: "コメントを削除します。よろしいですか？"}, class: 'btn btn-outline-info delete'
    br

app/views/comments/index.js.slim
| $("#comments_area").html("#{j(render 'index', { comments: @comment.post.comments })}");
| $("textarea").val('');

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Lesson
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    script crossorigin="anonymous" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    script crossorigin="anonymous" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
    script crossorigin="anonymous" integrity="sha384-o+RDsa0aLu++PJvFqy8fFScvbHFLtbvScb8AjopnFD+iEQ7wo/CG0xlczd+2O/em" src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.2/js/bootstrap.min.js"
    / font awesome
    link crossorigin="anonymous" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" rel="stylesheet" /
    / Bootstrap Material DatePicker
    link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/css/bootstrap-material-datetimepicker.min.css" rel="stylesheet" /
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" /
    script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.0/jquery.min.js" type="text/javascript"
    script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/moment.min.js" type="text/javascript"
    script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-material-datetimepicker/2.7.1/js/bootstrap-material-datetimepicker.min.js" type="text/javascript";
    script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.20.1/locale/ja.js" type="text/javascript"
  body
    .app-title.navbar.navbar-expand-lg.navbar-dark.fixed-top.bg-dark
      .container
        a.navbar-brand href= "/posts"
          span style=("font-size: 1.5em; color: white;")
            i.fas.fa-laptop-code
            | Lesson
        button.navbar-toggler aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" data-target="#navbar" data-toggle="collapse" type="button"
          span.navbar-toggler-icon
        #navbar.collapse.navbar-collapse
          ul.navbar-nav.mr-auto
            - if user_signed_in?
              / li.nav-item= strong= link_to current_user.username, edit_user_registration_path, class: 'nav-link'
              li.nav-item= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'nav-link'
            - else
              li.nav-item= link_to '新規登録', new_user_registration_path, class: 'nav-link'
              li.nav-item= link_to 'ログイン', new_user_session_path, class: 'nav-link'
            li.nav-item= link_to 'Lessonとは', about_index_path, class: 'nav-link'
          = search_form_for @q, class: 'form-inline' do |f|
            .form-group.row.my-auto.ml-lg-auto.mb-md-2
              .col-8
                = f.search_field :tags_name_cont, class: "form-control mr-lg-2", placeholder: 'タグで検索'
              .col-1
                = f.submit class: "btn btn-outline-info"
          .circle-avatar.index-field
            = link_to edit_user_registration_path
              - if user_signed_in? && current_user.avatar?
                = image_tag current_user.avatar.to_s
              - elsif user_signed_in?
                = image_tag "no_avatar.png"
    .container.header
      - if flash.notice.present?
        .alert.alert-success= flash.notice
      = yield
      footer.footer.fixed-bottom.py-3.bg-light
        .container.text-center
          span.text-dark © 2019 REONA

app/views/likes/_like.html.slim
- if user_signed_in?
  - unless post.like_user(current_user.id).blank?
    = link_to post_like_path(post_id: post.id, id: post.likes[0].id), method: :delete, remote: true do
      .vertical_liked
        i.fas.fa-thumbs-up.fa-lg.fa-fw
        span
          = post.likes_count
  - else
    = link_to post_likes_path(post.id), method: :post, remote: true do
      .vertical_like
        i.far.fa-thumbs-up.fa-lg.fa-fw
        span
          = post.likes_count
- else
  - if post.likes_count > 0
    .vertical_liked
      i.fas.fa-thumbs-up.fa-lg.fa-fw
      span
        = post.likes_count
  - else
    .vertical_like
      i.far.fa-thumbs-up.fa-lg.fa-fw
      span
        = post.likes_count

app/views/likes/create.html.slim
h1 Likes#create
p Find me in app/views/likes/create.html.slim

app/views/likes/create.js.slim
| $("#likes_buttons_#{@post.id}").html("#{j(render partial: 'likes/like', locals: { post: @post })}");

app/views/likes/destroy.js.slim
| $("#likes_buttons_#{@post.id}").html("#{j(render partial: 'likes/like', locals: { post: @post })}");

app/views/pages/show.html.slim
.container
  .row
    .col-xs-12.col-md-4
      .circle-avatar.field
        - if @user.avatar?
          = image_tag @user.avatar.to_s
        - else
          = image_tag "no_avatar.png"
      br
      table.table.table-hover
        tbody
          tr
            / th= User.human_attribute_name(:username)
            td= @user.username
          tr
            / th= User.human_attribute_name(:description)
            td= @user.description
    .col-xs-12.col-md-8.border-left
      h3.border-bottom #{@user.username} さんの投稿
      br
      .mb-3
        - @user.posts.each do |post|
          .posts_container.py-3
            .flex_container_main.py-2
              .name
                = link_to post.name, post, class: 'font-weight-bold'
              .tag_list
                = render partial: 'posts/tag_list', locals: { tag_list: post.tag_list }
              .description
                = post.description
            .flex_container_sub
              .index-field
              div id= "likes_buttons_#{post.id}"
                = render partial: 'likes/like', locals: { post: post, likes: @likes }
                / コメント数表
              .comment
                i.far.fa-comment.fa-lg.fa-fw
                span
                  = post.comments_count
              .item.ml-auto
                - if user_signed_in? && post.user_id == current_user.id
                  .post_edit
                    = link_to '編集', edit_post_path(post), class: 'btn btn-info mr-1'
                    = link_to '削除', post, method: :delete, remote: true, data: { confirm: "レッスン「#{post.name}」を削除します。よろしいですか？"}, class: 'btn btn-outline-info delete'
            .flex_container_sub
              .username
                = link_to post.user.username, page_path(post.user_id)
              .created_at.ml-auto
                = post.created_at

app/views/posts/_form.html.slim
- if post.errors.present?
  ul#error_explanation
    - post.errors.full_messages.each do |message|
      li= message

= form_with model: post, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'post_name', placeholder: 'Rubyの基礎を教えます！'
  .form-group
    = f.label :tag_list
    = f.text_field :tag_list, value: @post.tag_list.join(','), class: "form-control", placeholder: "内容に関連したタグをカンマ（,）区切りで入力してください。（例: Ruby,Python3）"
  .form-group
    = f.label :description
    = f.text_area :description, rows: 10, class: 'form-control', id: 'post_description'
  .form-group
    = f.label :lesson_at
    = f.text_field :lesson_at, class: 'form-control', id: 'post_lesson_at'
  .form-group
    = f.label :place
    = f.select :place,
      [["渋谷・目黒・世田谷"], ["新宿・中野・杉並・吉祥寺"], ["六本木・麻生・赤坂・青山"], ["銀座・日本橋・東京駅周辺"],
      ["池袋・目白・板橋・赤羽"], ["お台場・汐留・新橋・品川"], ["上野・浅草・両国"], ["御茶ノ水・湯島・九段・後楽園"],
      ["葛飾・江戸川・江東"], ["蒲田・大森・羽田周辺"], ["八王子・立川・町田・府中・調布"], ["東京"],
      ["北海道"], ["青森県"], ["岩手県"], ["宮城県"], ["秋田県"], ["山形県"], ["福島県"],
      ["茨城県"], ["栃木県"], ["群馬県"], ["埼玉県"], ["千葉県"], ["神奈川県"],
      ["新潟県"], ["富山県"], ["石川県"], ["福井県"], ["山梨県"], ["長野県"], ["岐阜県"],
      ["静岡県"], ["愛知県"], ["三重県"], ["滋賀県"], ["京都府"], ["大阪府"], ["兵庫県"],
      ["奈良県"], ["和歌山県"], ["鳥取県"], ["島根県"], ["岡山県"], ["広島県"], ["山口県"],
      ["徳島県"], ["香川県"], ["愛媛県"], ["高知県"], ["福岡県"], ["佐賀県"], ["長崎県"],
      ["熊本県"], ["大分県"], ["宮崎県"], ["鹿児島県"], ["沖縄県"]], { prompt: "エリアを選択してください" }, class: 'form-control', id: 'post_place'
  = f.submit nil, class: 'btn btn-info'

app/views/posts/_tag_list.html.slim
- tag_list.each do |tag|
  span.badge.badge-info.mr-1.p-2
    = link_to tag, posts_path(tag_name: tag), class: "text-white"

app/views/posts/destroy.js.slim
| $("#post-#{@post_id}").html('');

app/views/posts/edit.html.slim
h1 レッスンの編集

.nav.justify-content-end
  = link_to 'レッスン一覧', posts_path, class: 'nav-link'

= render partial: 'form', locals: { post: @post }

app/views/posts/index.html.slim
.container
  .row
    .col-12
        .shadow-lg.p-3.mb-5.bg-dark.rounded.text-center
          .container.p-4
            p.text-white.mb-2
              |Lessonはオフライン上での授業の場を提供するサービスです。
            br
            - if user_signed_in?
              = link_to 'レッスンを投稿する', new_post_path, class: 'btn btn-outline-info'
            - else
              = link_to "Lesson に登録する", new_user_registration_path, class: 'btn btn-outline-info'
    .col-xs-12.col-md-8.border-right
      h3.border-bottom ピックアップ記事
      br
      .mb-3
        - @posts.each do |post|
          .posts_container.py-3 id="post-#{post.id}"
            .flex_container_main.py-2
              .name
                = link_to post.name, post, class: 'font-weight-bold'
              .tag_list
                = render partial: 'posts/tag_list', locals: { tag_list: post.tag_list }
              .description
                = post.description
            .flex_container_sub
              .circle-avatar.index-field
                - if post.user.avatar?
                  = image_tag post.user.avatar.to_s
                - else
                  = image_tag "no_avatar.png"
                  / いいね表示
              div.pl-3 id= "likes_buttons_#{post.id}"
                = render partial: 'likes/like', locals: { post: post, likes: @likes }
              .comment
                i.far.fa-comment.fa-lg.fa-fw
                span
                  = post.comments_count
              .item.ml-auto
                - if user_signed_in? && post.user_id == current_user.id
                  .post_edit
                    = link_to '編集', edit_post_path(post), class: 'btn btn-info mr-1'
                    = link_to '削除', post, method: :delete, remote: true, data: { confirm: "レッスン「#{post.name}」を削除します。よろしいですか？"}, class: 'btn btn-outline-info delete'
            .flex_container_sub
              .username
                = link_to post.user.username, page_path(post.user_id)
              .created_at.ml-auto
                = post.created_at
      .container.mt-3
      = paginate @posts
      = page_entries_info @posts
    .col-xs-12.col-md-4
      h4.border-bottom.mb-3 タグ一覧
      - ActsAsTaggableOn::Tag.all.each do |tag|
        span.badge.badge-info.mr-1.mb-1.p-2
          = link_to tag, posts_path(tag_name: tag.name), class: "text-white"

app/views/posts/new.html.slim
h1 レッスンの作成

.nav.justify-content-end
  = link_to 'レッスン一覧', posts_path, class: 'nav-link'

= render partial: 'form', locals: { post: @post }

app/views/posts/show.html.slim
h1 レッスンの詳細

.nav.justify-content-end
  = link_to 'レッスン一覧', posts_path, class: 'nav-link'
  / いいね表示
  div id= "likes_buttons_#{@post.id}"
    = render partial: 'likes/like', locals: { post: @post, likes: @likes }
table.table.table-hover
  tbody
    tr
      th= User.human_attribute_name(:username)
      td= @post.user.username
    tr
      th= Post.human_attribute_name(:name)
      td= @post.name
    tr
      th= Post.human_attribute_name(:tag_list)
      td= render partial: 'posts/tag_list', locals: { tag_list: @post.tag_list }
    tr
      th= Post.human_attribute_name(:description)
      td= auto_link(simple_format(h(@post.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      th= Post.human_attribute_name(:place)
      td= @post.place
    tr
      th= Post.human_attribute_name(:lesson_at)
      td= @post.lesson_at
    tr
      th= Post.human_attribute_name(:created_at)
      td= @post.created_at
- if user_signed_in? && @post.user_id == current_user.id
  = link_to '編集', edit_post_path, class: 'btn btn-info mr-3'
  = link_to '削除', @post, method: :delete, data: { confirm: "レッスン「#{@post.name}」を削除します。よろしいですか？"}, class: 'btn btn-outline-info'
div
  br
  /! 投稿されたコメント一覧を詳細ページに表示するためのrender
  div id= "comments_area"
    = render partial: 'comments/index', locals: { comments: @comments }
  - if user_signed_in?
    br
    /! コメント入力欄を詳細ページに表示するためのrender
    = render partial: 'comments/form', locals: { comment: @comment, post: @post }